vo=gpu-next
gpu-api=d3d11
vd-lavc-dr=yes   
gpu-context=auto
slang=en
sub-auto=fuzzy

[yt]
ytdl-raw-options=cookies-from-browser=firefox,downloader=ffmpeg,mark-watched=,extractor-args="youtube:skip=hls",format="bestvideo+bestaudio/best",format-sort="proto",sub-lang=en,write-sub=,write-auto-sub=,js-runtimes="deno:/usr/bin/deno",remote-components=ejs:npm
#ytdl-raw-options=config-location="~/.config/mpv/yt-dlp.conf"
#requires firefox, deno and ffmpeg to be installed
