# hyprlang noerror false
# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

#Execs built for main PC
# exec-once = steam -silent
# exec-once = screen -dm sh ~/Documents/sunshine/start.sh 
# exec-once = MoonDeckBuddy
# exec-once = app2unit -- corectrl --minimize-systray
# exec-once = vesktop
