




















 Close active window

 Kill hyprland 

 Toggle window floating

 Toggle fullscreen

 Start hyprlock

 Show logout/power menu



 Launch terminal

 Launch file manager

 Launch text editor

 Launch web browser

 Launch system monitor

 Launch color picker

 Take a screenshot



 Show app drawer

 Show window switcher






 Previous song/media

 Next song/media

 Play/pause song/media


 Move window focus up
 Move window focus down
 Move window focus left 
 Move window focus right


 Focus prevous monitor 
 Focus next monitor 


 Move to prevous workspace
 Move to next workspace 
 Move to prevous workspace (scroll)
 Move to next workspace (scroll)


 Move focused window to prevous workspace
 Move focused window to next workspace
 Move focused window to prevous workspace silently
 Move focused window to next workspace silently 


 Move window (mouse) 
 Resize window (mouse)
 Move window (keyboard)
 Resize window (keyboard) 


 Toggle window split direction





















